// ============================================================
// OIOS Client Dashboard — Demo Seed Data
// Mike's Plumbing, Gilbert AZ
// ============================================================

import type {
  Organization, User, Call, Lead, Customer, Appointment,
  Invoice, Review, ActivityFeedItem, TeamMember,
} from './types'

const ORG_ID = 'demo-org-mikes-plumbing'
const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString()
const minsAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString()

export const demoOrg: Organization = {
  id: ORG_ID,
  name: "Mike's Plumbing",
  slug: 'mikes-plumbing',
  trade: 'plumbing',
  tier: 'office_manager',
  phone_number: '(480) 555-0199',
  forwarding_number: '(480) 555-0200',
  timezone: 'America/Phoenix',
  business_hours: {
    mon: { open: '07:00', close: '18:00' },
    tue: { open: '07:00', close: '18:00' },
    wed: { open: '07:00', close: '18:00' },
    thu: { open: '07:00', close: '18:00' },
    fri: { open: '07:00', close: '17:00' },
    sat: { open: '08:00', close: '14:00' },
    sun: { open: 'closed', close: 'closed' },
  },
  service_area: ['85233', '85234', '85295', '85296', '85297', '85298', '85224', '85225'],
  services_offered: ['Drain Cleaning', 'Water Heater Install', 'Leak Repair', 'Sewer Line', 'Faucet Install', 'Toilet Repair', 'Garbage Disposal', 'Repiping', 'Emergency Plumbing'],
  emergency_keywords: ['flood', 'burst', 'sewage', 'no water', 'gas leak', 'emergency'],
  emergency_phone: '(480) 555-0101',
  ai_agent_name: 'Sarah',
  ai_agent_voice_id: 'oios-sarah-v2',
  ai_agent_personality: 'Warm, professional, and knowledgeable about plumbing services. Speaks with confidence and empathy.',
  onboarding_status: 'live',
  stripe_customer_id: null,
  stripe_subscription_id: null,
  monthly_minutes_included: 500,
  monthly_minutes_used: 247,
  created_at: daysAgo(90),
  updated_at: daysAgo(1),
}

export const demoUsers: User[] = [
  { id: 'user-mike', organization_id: ORG_ID, full_name: 'Mike Rodriguez', email: 'mike@mikesplumbing.com', phone: '(480) 555-0101', role: 'owner', avatar_url: null, notification_preferences: { sms: true, email: true, daily_digest: true, weekly_report: true }, created_at: daysAgo(90) },
  { id: 'user-jake', organization_id: ORG_ID, full_name: 'Jake Thompson', email: 'jake@mikesplumbing.com', phone: '(480) 555-0102', role: 'technician', avatar_url: null, notification_preferences: { sms: true, email: false }, created_at: daysAgo(60) },
  { id: 'user-carlos', organization_id: ORG_ID, full_name: 'Carlos Mendez', email: 'carlos@mikesplumbing.com', phone: '(480) 555-0103', role: 'technician', avatar_url: null, notification_preferences: { sms: true, email: false }, created_at: daysAgo(45) },
]

export const demoCustomers: Customer[] = [
  { id: 'cust-1', organization_id: ORG_ID, first_name: 'Lisa', last_name: 'Martinez', phone: '(480) 555-1001', email: 'lisa.m@email.com', address: '1234 E Guadalupe Rd, Gilbert AZ 85234', notes: 'Has 2 kids (Tommy and Sarah), golden retriever named Max. Prefers morning appointments.', tags: ['VIP', 'repeat'], total_jobs: 5, total_revenue: 2850, lifetime_value: 3200, first_contact_at: daysAgo(180), last_contact_at: daysAgo(3), satisfaction_score: 9.5, created_at: daysAgo(180), updated_at: daysAgo(3) },
  { id: 'cust-2', organization_id: ORG_ID, first_name: 'John', last_name: 'Davis', phone: '(480) 555-1002', email: 'johnd@email.com', address: '5678 S Val Vista Dr, Gilbert AZ 85296', notes: 'Retired firefighter. Likes to chat. Always pays same day.', tags: ['repeat'], total_jobs: 3, total_revenue: 1450, lifetime_value: 1800, first_contact_at: daysAgo(120), last_contact_at: daysAgo(7), satisfaction_score: 10, created_at: daysAgo(120), updated_at: daysAgo(7) },
  { id: 'cust-3', organization_id: ORG_ID, first_name: 'Sarah', last_name: 'Chen', phone: '(480) 555-1003', email: 'schen@email.com', address: '910 W Elliot Rd, Gilbert AZ 85233', notes: 'Property manager — manages 12 rental units. High-volume potential.', tags: ['VIP', 'property_manager'], total_jobs: 8, total_revenue: 4200, lifetime_value: 6500, first_contact_at: daysAgo(200), last_contact_at: daysAgo(1), satisfaction_score: 9.0, created_at: daysAgo(200), updated_at: daysAgo(1) },
  { id: 'cust-4', organization_id: ORG_ID, first_name: 'Robert', last_name: 'Williams', phone: '(480) 555-1004', email: null, address: '321 N Lindsay Rd, Gilbert AZ 85234', notes: 'Older home, galvanized pipes. May need full repipe soon.', tags: ['upsell_opportunity'], total_jobs: 2, total_revenue: 680, lifetime_value: 680, first_contact_at: daysAgo(30), last_contact_at: daysAgo(14), satisfaction_score: 8.0, created_at: daysAgo(30), updated_at: daysAgo(14) },
  { id: 'cust-5', organization_id: ORG_ID, first_name: 'Maria', last_name: 'Gonzalez', phone: '(480) 555-1005', email: 'maria.g@email.com', address: '444 E Warner Rd, Gilbert AZ 85297', notes: 'Speaks English and Spanish. Prefers afternoon appointments.', tags: ['repeat'], total_jobs: 4, total_revenue: 1920, lifetime_value: 2100, first_contact_at: daysAgo(150), last_contact_at: daysAgo(5), satisfaction_score: 9.2, created_at: daysAgo(150), updated_at: daysAgo(5) },
  { id: 'cust-6', organization_id: ORG_ID, first_name: 'David', last_name: 'Park', phone: '(480) 555-1006', email: 'dpark@email.com', address: '789 E Baseline Rd, Gilbert AZ 85233', notes: 'New homeowner. Just moved from California.', tags: ['new'], total_jobs: 1, total_revenue: 250, lifetime_value: 250, first_contact_at: daysAgo(10), last_contact_at: daysAgo(10), satisfaction_score: null, created_at: daysAgo(10), updated_at: daysAgo(10) },
  { id: 'cust-7', organization_id: ORG_ID, first_name: 'Jennifer', last_name: 'Thompson', phone: '(480) 555-1007', email: 'jthompson@email.com', address: '555 S Higley Rd, Gilbert AZ 85296', notes: 'Allergic to strong chemicals. Use eco-friendly products only.', tags: ['eco_conscious'], total_jobs: 2, total_revenue: 890, lifetime_value: 890, first_contact_at: daysAgo(60), last_contact_at: daysAgo(20), satisfaction_score: 8.5, created_at: daysAgo(60), updated_at: daysAgo(20) },
  { id: 'cust-8', organization_id: ORG_ID, first_name: 'Tom', last_name: 'Baker', phone: '(480) 555-1008', email: 'tbaker@email.com', address: '222 W Ray Rd, Gilbert AZ 85295', notes: 'Restaurant owner — Gilbert Grill. Commercial plumbing needs.', tags: ['commercial', 'VIP'], total_jobs: 6, total_revenue: 5400, lifetime_value: 7200, first_contact_at: daysAgo(240), last_contact_at: daysAgo(2), satisfaction_score: 9.8, created_at: daysAgo(240), updated_at: daysAgo(2) },
  { id: 'cust-9', organization_id: ORG_ID, first_name: 'Angela', last_name: 'Foster', phone: '(480) 555-1009', email: null, address: '888 E Pecos Rd, Gilbert AZ 85297', notes: null, tags: [], total_jobs: 1, total_revenue: 175, lifetime_value: 175, first_contact_at: daysAgo(5), last_contact_at: daysAgo(5), satisfaction_score: null, created_at: daysAgo(5), updated_at: daysAgo(5) },
  { id: 'cust-10', organization_id: ORG_ID, first_name: 'Kevin', last_name: 'Nguyen', phone: '(480) 555-1010', email: 'knguyen@email.com', address: '333 N Power Rd, Gilbert AZ 85234', notes: 'Tech-savvy, prefers text communication.', tags: ['referral_source'], total_jobs: 3, total_revenue: 1340, lifetime_value: 1500, first_contact_at: daysAgo(90), last_contact_at: daysAgo(8), satisfaction_score: 9.0, created_at: daysAgo(90), updated_at: daysAgo(8) },
]

export const demoCalls: Call[] = [
  { id: 'call-1', organization_id: ORG_ID, external_call_id: 'oios-c-001', caller_phone: '(480) 555-1001', caller_name: 'Lisa Martinez', direction: 'inbound', status: 'answered', duration_seconds: 187, started_at: minsAgo(45), ended_at: minsAgo(42), recording_url: null, transcript: 'Sarah: Good morning, Mike\'s Plumbing! This is Sarah, how can I help you today?\nLisa: Hi Sarah, it\'s Lisa Martinez. My kitchen faucet has been dripping for a couple days now.\nSarah: Oh hi Lisa! I\'m sorry to hear about the dripping faucet. Let me get you scheduled to have that taken care of. Are mornings still best for you?\nLisa: Yes, mornings are perfect. Do you have anything this week?\nSarah: I have Thursday at 9 AM available with Jake. Would that work for you?\nLisa: That\'s great. Thank you Sarah!\nSarah: Perfect! I\'ve got you down for Thursday at 9 AM. Jake will be there. Is there anything else I can help with?\nLisa: No, that\'s it. Thanks!', transcript_summary: 'Lisa Martinez called about a dripping kitchen faucet. Sarah scheduled an appointment with Jake for Thursday at 9 AM. Lisa prefers morning appointments.', sentiment: 'positive', intent: 'schedule_appointment', extracted_data: { service_needed: 'Faucet Repair', urgency: 'moderate', address: '1234 E Guadalupe Rd, Gilbert AZ 85234', preferred_time: 'morning', estimated_value: 250 }, ai_agent_handled: true, escalated_to_human: false, escalation_reason: null, lead_id: 'lead-1', appointment_id: 'apt-1', tags: ['repeat_customer'], created_at: minsAgo(45) },
  { id: 'call-2', organization_id: ORG_ID, external_call_id: 'oios-c-002', caller_phone: '(480) 555-2001', caller_name: null, direction: 'inbound', status: 'answered', duration_seconds: 243, started_at: hoursAgo(2), ended_at: hoursAgo(2), recording_url: null, transcript: null, transcript_summary: 'New caller inquired about water heater replacement cost. Sarah provided a price range ($800-$1,500 depending on model) and captured lead info. Caller interested in a quote.', sentiment: 'neutral', intent: 'get_quote', extracted_data: { service_needed: 'Water Heater Replacement', urgency: 'low', estimated_value: 1200 }, ai_agent_handled: true, escalated_to_human: false, escalation_reason: null, lead_id: 'lead-2', appointment_id: null, tags: ['new_lead'], created_at: hoursAgo(2) },
  { id: 'call-3', organization_id: ORG_ID, external_call_id: 'oios-c-003', caller_phone: '(480) 555-1008', caller_name: 'Tom Baker', direction: 'inbound', status: 'answered', duration_seconds: 312, started_at: hoursAgo(4), ended_at: hoursAgo(4), recording_url: null, transcript: null, transcript_summary: 'Tom Baker from Gilbert Grill called about a grease trap issue. His commercial kitchen drain is backing up. Sarah flagged this as urgent and scheduled same-day service with Jake.', sentiment: 'urgent', intent: 'emergency', extracted_data: { service_needed: 'Commercial Drain Cleaning', urgency: 'high', address: '222 W Ray Rd, Gilbert AZ 85295', estimated_value: 450 }, ai_agent_handled: true, escalated_to_human: false, escalation_reason: null, lead_id: null, appointment_id: 'apt-2', tags: ['commercial', 'urgent'], created_at: hoursAgo(4) },
  { id: 'call-4', organization_id: ORG_ID, external_call_id: 'oios-c-004', caller_phone: '(480) 555-3001', caller_name: null, direction: 'inbound', status: 'missed', duration_seconds: 0, started_at: hoursAgo(6), ended_at: hoursAgo(6), recording_url: null, transcript: null, transcript_summary: null, sentiment: 'neutral', intent: null, extracted_data: null, ai_agent_handled: false, escalated_to_human: false, escalation_reason: null, lead_id: null, appointment_id: null, tags: ['missed'], created_at: hoursAgo(6) },
  { id: 'call-5', organization_id: ORG_ID, external_call_id: 'oios-c-005', caller_phone: '(480) 555-1003', caller_name: 'Sarah Chen', direction: 'inbound', status: 'answered', duration_seconds: 198, started_at: daysAgo(1), ended_at: daysAgo(1), recording_url: null, transcript: null, transcript_summary: 'Sarah Chen (property manager) called to schedule maintenance for 3 rental units. Sarah booked back-to-back appointments for next Monday.', sentiment: 'positive', intent: 'schedule_appointment', extracted_data: { service_needed: 'Maintenance Inspection', urgency: 'low', estimated_value: 525 }, ai_agent_handled: true, escalated_to_human: false, escalation_reason: null, lead_id: null, appointment_id: 'apt-3', tags: ['property_manager', 'multi_unit'], created_at: daysAgo(1) },
  { id: 'call-6', organization_id: ORG_ID, external_call_id: 'oios-c-006', caller_phone: '(480) 555-1005', caller_name: 'Maria Gonzalez', direction: 'inbound', status: 'answered', duration_seconds: 156, started_at: daysAgo(2), ended_at: daysAgo(2), recording_url: null, transcript: null, transcript_summary: 'Maria Gonzalez called about a running toilet. Sarah scheduled a repair for Wednesday afternoon and reminded Maria about the eco-friendly products note on file.', sentiment: 'positive', intent: 'schedule_appointment', extracted_data: { service_needed: 'Toilet Repair', urgency: 'moderate', estimated_value: 175 }, ai_agent_handled: true, escalated_to_human: false, escalation_reason: null, lead_id: null, appointment_id: 'apt-4', tags: ['repeat_customer'], created_at: daysAgo(2) },
  { id: 'call-7', organization_id: ORG_ID, external_call_id: 'oios-c-007', caller_phone: '(480) 555-4001', caller_name: null, direction: 'inbound', status: 'answered', duration_seconds: 420, started_at: daysAgo(3), ended_at: daysAgo(3), recording_url: null, transcript: null, transcript_summary: 'New caller with a complex sewer line issue. Sarah gathered details and escalated to Mike for a personal callback. Potential high-value job ($3,000+).', sentiment: 'negative', intent: 'get_quote', extracted_data: { service_needed: 'Sewer Line Repair', urgency: 'high', estimated_value: 3500 }, ai_agent_handled: true, escalated_to_human: true, escalation_reason: 'High-value complex job requiring owner consultation', lead_id: 'lead-3', appointment_id: null, tags: ['escalated', 'high_value'], created_at: daysAgo(3) },
]

export const demoLeads: Lead[] = [
  { id: 'lead-1', organization_id: ORG_ID, customer_id: 'cust-1', source: 'phone_call', status: 'qualified', priority: 'warm', score: 72, score_reasons: ['Repeat customer', 'Clear service need', 'Appointment booked'], name: null, first_name: 'Lisa', last_name: 'Martinez', phone: '(480) 555-1001', email: 'lisa.m@email.com', company: null, lead_type: null, address: '1234 E Guadalupe Rd, Gilbert AZ 85234', service_needed: 'Kitchen Faucet Repair', estimated_value: 250, notes: 'Dripping faucet for 2 days. Prefers mornings.', follow_up_date: null, follow_up_count: 0, last_contact_at: minsAgo(45), won_at: null, lost_at: null, lost_reason: null, assigned_to: 'user-jake', created_at: minsAgo(45), updated_at: minsAgo(45) },
  { id: 'lead-2', organization_id: ORG_ID, customer_id: null, source: 'phone_call', status: 'new', priority: 'hot', score: 85, score_reasons: ['High-value service', 'Active inquiry', 'Ready to schedule'], name: null, first_name: 'Mark', last_name: 'Peterson', phone: '(480) 555-2001', email: null, company: null, lead_type: null, address: null, service_needed: 'Water Heater Replacement', estimated_value: 1200, notes: 'Inquired about costs. Current heater is 15 years old.', follow_up_date: daysAgo(-1), follow_up_count: 0, last_contact_at: hoursAgo(2), won_at: null, lost_at: null, lost_reason: null, assigned_to: null, created_at: hoursAgo(2), updated_at: hoursAgo(2) },
  { id: 'lead-3', organization_id: ORG_ID, customer_id: null, source: 'phone_call', status: 'contacted', priority: 'hot', score: 91, score_reasons: ['High estimated value', 'Urgent need', 'Owner escalation'], name: null, first_name: 'Brandon', last_name: 'Stewart', phone: '(480) 555-4001', email: 'bstewart@email.com', company: null, lead_type: null, address: '1500 E Chandler Blvd, Gilbert AZ', service_needed: 'Sewer Line Repair', estimated_value: 3500, notes: 'Complex sewer issue. Escalated to Mike for callback.', follow_up_date: daysAgo(0), follow_up_count: 1, last_contact_at: daysAgo(2), won_at: null, lost_at: null, lost_reason: null, assigned_to: 'user-mike', created_at: daysAgo(3), updated_at: daysAgo(2) },
  { id: 'lead-4', organization_id: ORG_ID, customer_id: 'cust-6', source: 'web_form', status: 'proposal_sent', priority: 'warm', score: 65, score_reasons: ['New customer', 'Moderate value', 'Proposal sent'], name: null, first_name: 'David', last_name: 'Park', phone: '(480) 555-1006', email: 'dpark@email.com', company: null, lead_type: null, address: '789 E Baseline Rd, Gilbert AZ 85233', service_needed: 'Whole House Inspection', estimated_value: 400, notes: 'New homeowner wants full plumbing inspection.', follow_up_date: daysAgo(-2), follow_up_count: 2, last_contact_at: daysAgo(3), won_at: null, lost_at: null, lost_reason: null, assigned_to: 'user-mike', created_at: daysAgo(10), updated_at: daysAgo(3) },
  { id: 'lead-5', organization_id: ORG_ID, customer_id: null, source: 'referral', status: 'won', priority: 'warm', score: 78, score_reasons: ['Referral source', 'Completed job'], name: null, first_name: 'Amanda', last_name: 'Collins', phone: '(480) 555-5001', email: 'acollins@email.com', company: null, lead_type: null, address: '600 S Gilbert Rd, Gilbert AZ', service_needed: 'Garbage Disposal Install', estimated_value: 350, notes: 'Referred by Kevin Nguyen.', follow_up_date: null, follow_up_count: 1, last_contact_at: daysAgo(7), won_at: daysAgo(7), lost_at: null, lost_reason: null, assigned_to: 'user-carlos', created_at: daysAgo(14), updated_at: daysAgo(7) },
  { id: 'lead-6', organization_id: ORG_ID, customer_id: null, source: 'social_media', status: 'lost', priority: 'cold', score: 25, score_reasons: ['Low engagement', 'Price sensitive', 'No follow-up response'], name: null, first_name: 'Greg', last_name: 'Hill', phone: '(480) 555-6001', email: null, company: null, lead_type: null, address: null, service_needed: 'Repiping Quote', estimated_value: 5000, notes: 'Found on Facebook. Asked for quote but ghosted after seeing price.', follow_up_date: null, follow_up_count: 3, last_contact_at: daysAgo(20), won_at: null, lost_at: daysAgo(15), lost_reason: 'Price too high / No response', assigned_to: null, created_at: daysAgo(25), updated_at: daysAgo(15) },
  { id: 'lead-7', organization_id: ORG_ID, customer_id: null, source: 'marketing_campaign', status: 'new', priority: 'warm', score: 58, score_reasons: ['Campaign response', 'Active homeowner'], name: null, first_name: 'Rachel', last_name: 'Young', phone: '(480) 555-7001', email: 'ryoung@email.com', company: null, lead_type: null, address: '900 E Ocotillo Rd, Gilbert AZ', service_needed: 'Water Softener Install', estimated_value: 800, notes: 'Responded to spring maintenance mailer.', follow_up_date: daysAgo(-1), follow_up_count: 0, last_contact_at: daysAgo(2), won_at: null, lost_at: null, lost_reason: null, assigned_to: null, created_at: daysAgo(2), updated_at: daysAgo(2) },
]

export const demoAppointments: Appointment[] = [
  { id: 'apt-1', organization_id: ORG_ID, customer_id: 'cust-1', lead_id: 'lead-1', assigned_to: 'user-jake', service_type: 'Kitchen Faucet Repair', status: 'scheduled', scheduled_date: daysAgo(-2).split('T')[0], scheduled_time_start: '09:00', scheduled_time_end: '10:30', actual_start: null, actual_end: null, address: '1234 E Guadalupe Rd, Gilbert AZ 85234', estimated_value: 250, actual_value: null, notes: 'Dripping faucet. Customer prefers mornings. Has golden retriever — be careful opening door.', reminder_sent: true, confirmation_sent: true, customer_confirmed: true, created_by: 'Sarah', created_at: minsAgo(45), updated_at: minsAgo(45) },
  { id: 'apt-2', organization_id: ORG_ID, customer_id: 'cust-8', lead_id: null, assigned_to: 'user-jake', service_type: 'Commercial Drain Cleaning', status: 'in_progress', scheduled_date: new Date().toISOString().split('T')[0], scheduled_time_start: '11:00', scheduled_time_end: '13:00', actual_start: hoursAgo(1), actual_end: null, address: '222 W Ray Rd, Gilbert AZ 85295', estimated_value: 450, actual_value: null, notes: 'Gilbert Grill — grease trap backup. Urgent. Use back entrance.', reminder_sent: false, confirmation_sent: true, customer_confirmed: true, created_by: 'Sarah', created_at: hoursAgo(4), updated_at: hoursAgo(1) },
  { id: 'apt-3', organization_id: ORG_ID, customer_id: 'cust-3', lead_id: null, assigned_to: 'user-carlos', service_type: 'Maintenance Inspection', status: 'scheduled', scheduled_date: daysAgo(-4).split('T')[0], scheduled_time_start: '08:00', scheduled_time_end: '15:00', actual_start: null, actual_end: null, address: 'Multiple units — see notes', estimated_value: 525, actual_value: null, notes: '3 rental units for Sarah Chen. Unit 1: 910 W Elliot Rd #101, Unit 2: #103, Unit 3: #107. Allow 2 hours per unit.', reminder_sent: false, confirmation_sent: false, customer_confirmed: false, created_by: 'Sarah', created_at: daysAgo(1), updated_at: daysAgo(1) },
  { id: 'apt-4', organization_id: ORG_ID, customer_id: 'cust-5', lead_id: null, assigned_to: 'user-carlos', service_type: 'Toilet Repair', status: 'confirmed', scheduled_date: daysAgo(-1).split('T')[0], scheduled_time_start: '14:00', scheduled_time_end: '15:30', actual_start: null, actual_end: null, address: '444 E Warner Rd, Gilbert AZ 85297', estimated_value: 175, actual_value: null, notes: 'Running toilet. Use eco-friendly products — customer has chemical allergies.', reminder_sent: true, confirmation_sent: true, customer_confirmed: true, created_by: 'Sarah', created_at: daysAgo(2), updated_at: daysAgo(1) },
  { id: 'apt-5', organization_id: ORG_ID, customer_id: 'cust-2', lead_id: null, assigned_to: 'user-jake', service_type: 'Water Heater Flush', status: 'completed', scheduled_date: daysAgo(3).split('T')[0], scheduled_time_start: '10:00', scheduled_time_end: '11:30', actual_start: daysAgo(3), actual_end: daysAgo(3), address: '5678 S Val Vista Dr, Gilbert AZ 85296', estimated_value: 200, actual_value: 200, notes: 'Annual maintenance flush. Customer is chatty — allow extra time.', reminder_sent: true, confirmation_sent: true, customer_confirmed: true, created_by: 'Sarah', created_at: daysAgo(7), updated_at: daysAgo(3) },
]

export const demoInvoices: Invoice[] = [
  { id: 'inv-1', organization_id: ORG_ID, customer_id: 'cust-2', appointment_id: 'apt-5', invoice_number: 'INV-2026-0042', status: 'paid', amount: 200, amount_paid: 200, tax_amount: 17.40, line_items: [{ description: 'Water Heater Flush — Annual Maintenance', quantity: 1, unit_price: 200, total: 200 }], due_date: daysAgo(0).split('T')[0], sent_at: daysAgo(3), paid_at: daysAgo(3), payment_method: 'Credit Card', reminder_count: 0, last_reminder_at: null, notes: 'Paid same day', created_at: daysAgo(3), updated_at: daysAgo(3) },
  { id: 'inv-2', organization_id: ORG_ID, customer_id: 'cust-8', appointment_id: null, invoice_number: 'INV-2026-0041', status: 'sent', amount: 850, amount_paid: 0, tax_amount: 73.95, line_items: [{ description: 'Commercial Drain Cleaning', quantity: 1, unit_price: 650, total: 650 }, { description: 'Grease Trap Service', quantity: 1, unit_price: 200, total: 200 }], due_date: daysAgo(-14).split('T')[0], sent_at: daysAgo(5), paid_at: null, payment_method: null, reminder_count: 0, last_reminder_at: null, notes: 'Net 30 terms — commercial account', created_at: daysAgo(5), updated_at: daysAgo(5) },
  { id: 'inv-3', organization_id: ORG_ID, customer_id: 'cust-3', appointment_id: null, invoice_number: 'INV-2026-0039', status: 'overdue', amount: 1575, amount_paid: 0, tax_amount: 137.03, line_items: [{ description: 'Unit Inspection & Maintenance (3 units)', quantity: 3, unit_price: 525, total: 1575 }], due_date: daysAgo(7).split('T')[0], sent_at: daysAgo(21), paid_at: null, payment_method: null, reminder_count: 2, last_reminder_at: daysAgo(3), notes: 'Sarah Chen — property management account. Sent 2 reminders.', created_at: daysAgo(21), updated_at: daysAgo(3) },
  { id: 'inv-4', organization_id: ORG_ID, customer_id: 'cust-10', appointment_id: null, invoice_number: 'INV-2026-0038', status: 'paid', amount: 340, amount_paid: 340, tax_amount: 29.58, line_items: [{ description: 'Leak Detection & Repair', quantity: 1, unit_price: 340, total: 340 }], due_date: daysAgo(10).split('T')[0], sent_at: daysAgo(15), paid_at: daysAgo(12), payment_method: 'Check', reminder_count: 0, last_reminder_at: null, notes: null, created_at: daysAgo(15), updated_at: daysAgo(12) },
]

export const demoReviews: Review[] = [
  { id: 'rev-1', organization_id: ORG_ID, customer_id: 'cust-1', platform: 'google', rating: 5, review_text: 'Mike\'s team is incredible! Jake fixed our kitchen sink in under an hour. Sarah on the phone was so helpful scheduling everything. Highly recommend!', reviewer_name: 'Lisa M.', review_url: null, response_text: 'Thank you so much, Lisa! We\'re glad Jake could get that fixed quickly for you. We appreciate your continued trust in Mike\'s Plumbing!', response_status: 'posted', responded_at: daysAgo(5), sentiment: 'positive', review_date: daysAgo(7), request_sent: true, created_at: daysAgo(7) },
  { id: 'rev-2', organization_id: ORG_ID, customer_id: 'cust-8', platform: 'google', rating: 5, review_text: 'We use Mike\'s Plumbing for our restaurant. They always respond quickly and their work is top-notch. Commercial plumbing done right!', reviewer_name: 'Tom B.', review_url: null, response_text: 'Thanks Tom! Gilbert Grill is one of our favorite clients. We\'re always here when you need us!', response_status: 'posted', responded_at: daysAgo(10), sentiment: 'positive', review_date: daysAgo(12), request_sent: false, created_at: daysAgo(12) },
  { id: 'rev-3', organization_id: ORG_ID, customer_id: 'cust-4', platform: 'yelp', rating: 4, review_text: 'Good service but a bit pricey. They did fix the issue though and the technician was polite.', reviewer_name: 'Robert W.', review_url: null, response_text: 'Thank you for the feedback, Robert. We strive to provide the best value for quality plumbing work. We hope to exceed your expectations next time!', response_status: 'drafted', responded_at: null, sentiment: 'neutral', review_date: daysAgo(14), request_sent: true, created_at: daysAgo(14) },
  { id: 'rev-4', organization_id: ORG_ID, customer_id: 'cust-5', platform: 'google', rating: 5, review_text: 'Carlos was amazing! Very respectful of our home and used eco-friendly products when I asked. Will definitely call again.', reviewer_name: 'Maria G.', review_url: null, response_text: null, response_status: 'pending', responded_at: null, sentiment: 'positive', review_date: daysAgo(5), request_sent: true, created_at: daysAgo(5) },
  { id: 'rev-5', organization_id: ORG_ID, customer_id: null, platform: 'facebook', rating: 3, review_text: 'Had to call twice because the first appointment was rescheduled. Second time was fine though.', reviewer_name: 'James K.', review_url: null, response_text: 'We apologize for the rescheduling inconvenience, James. This isn\'t our standard and we\'ve taken steps to ensure it doesn\'t happen again. Thank you for giving us another chance.', response_status: 'drafted', responded_at: null, sentiment: 'negative', review_date: daysAgo(20), request_sent: false, created_at: daysAgo(20) },
]

export const demoActivity: ActivityFeedItem[] = [
  { id: 'act-1', organization_id: ORG_ID, actor: 'Sarah', action: 'answered a call from Lisa Martinez — Kitchen faucet repair, $250 estimated', entity_type: 'call', entity_id: 'call-1', metadata: { service: 'Faucet Repair', value: 250 }, importance: 'medium', read: false, created_at: minsAgo(45) },
  { id: 'act-2', organization_id: ORG_ID, actor: 'Sarah', action: 'booked Lisa Martinez for Thursday 9 AM — Kitchen Faucet Repair with Jake', entity_type: 'appointment', entity_id: 'apt-1', metadata: { tech: 'Jake', value: 250 }, importance: 'medium', read: false, created_at: minsAgo(44) },
  { id: 'act-3', organization_id: ORG_ID, actor: 'Sarah', action: 'captured new lead: Mark Peterson — Water Heater Replacement ($1,200)', entity_type: 'lead', entity_id: 'lead-2', metadata: { value: 1200, source: 'phone_call' }, importance: 'high', read: false, created_at: hoursAgo(2) },
  { id: 'act-4', organization_id: ORG_ID, actor: 'Sarah', action: 'flagged URGENT: Tom Baker — Commercial drain backup at Gilbert Grill', entity_type: 'call', entity_id: 'call-3', metadata: { urgency: 'high' }, importance: 'critical', read: true, created_at: hoursAgo(4) },
  { id: 'act-5', organization_id: ORG_ID, actor: 'Sarah', action: 'scheduled same-day emergency service for Tom Baker with Jake', entity_type: 'appointment', entity_id: 'apt-2', metadata: { tech: 'Jake' }, importance: 'high', read: true, created_at: hoursAgo(4) },
  { id: 'act-6', organization_id: ORG_ID, actor: 'Follow-Up Agent', action: 'sent follow-up SMS to 3 leads from yesterday', entity_type: 'follow_up', entity_id: null, metadata: { count: 3 }, importance: 'low', read: true, created_at: hoursAgo(8) },
  { id: 'act-7', organization_id: ORG_ID, actor: 'Review Manager', action: 'requested review from Maria Gonzalez after completed toilet repair', entity_type: 'review', entity_id: null, metadata: { customer: 'Maria Gonzalez' }, importance: 'low', read: true, created_at: daysAgo(1) },
  { id: 'act-8', organization_id: ORG_ID, actor: 'Sarah', action: 'escalated sewer line inquiry to Mike — Brandon Stewart, $3,500 estimated', entity_type: 'lead', entity_id: 'lead-3', metadata: { value: 3500, reason: 'High-value complex job' }, importance: 'critical', read: true, created_at: daysAgo(3) },
  { id: 'act-9', organization_id: ORG_ID, actor: 'Invoice Agent', action: 'sent payment reminder #2 to Sarah Chen — INV-2026-0039 ($1,575 overdue)', entity_type: 'invoice', entity_id: 'inv-3', metadata: { amount: 1575 }, importance: 'high', read: true, created_at: daysAgo(3) },
  { id: 'act-10', organization_id: ORG_ID, actor: 'System', action: 'John Davis paid INV-2026-0042 — $200 via Credit Card', entity_type: 'invoice', entity_id: 'inv-1', metadata: { amount: 200, method: 'Credit Card' }, importance: 'medium', read: true, created_at: daysAgo(3) },
]

export const demoTeam: TeamMember[] = [
  { id: 'tm-1', organization_id: ORG_ID, user_id: 'user-mike', name: 'Mike Rodriguez', phone: '(480) 555-0101', email: 'mike@mikesplumbing.com', role: 'Owner / Master Plumber', skills: ['Master Plumber License', 'Sewer & Drain', 'Water Heater', 'Gas Lines', 'Repiping', 'Commercial'], service_area: ['Gilbert', 'Mesa', 'Chandler', 'Queen Creek'], availability: { mon: '07:00-18:00', tue: '07:00-18:00', wed: '07:00-18:00', thu: '07:00-18:00', fri: '07:00-17:00' }, is_on_call: true, performance_score: 9.8, total_jobs_completed: 1247, average_review_score: 4.9, created_at: daysAgo(90) },
  { id: 'tm-2', organization_id: ORG_ID, user_id: 'user-jake', name: 'Jake Thompson', phone: '(480) 555-0102', email: 'jake@mikesplumbing.com', role: 'Lead Technician', skills: ['Journeyman Plumber', 'Drain Cleaning', 'Water Heater', 'Faucet/Fixture', 'Commercial'], service_area: ['Gilbert', 'Mesa', 'Chandler'], availability: { mon: '07:00-18:00', tue: '07:00-18:00', wed: '07:00-18:00', thu: '07:00-18:00', fri: '07:00-17:00', sat: '08:00-14:00' }, is_on_call: false, performance_score: 9.2, total_jobs_completed: 342, average_review_score: 4.8, created_at: daysAgo(60) },
  { id: 'tm-3', organization_id: ORG_ID, user_id: 'user-carlos', name: 'Carlos Mendez', phone: '(480) 555-0103', email: 'carlos@mikesplumbing.com', role: 'Apprentice', skills: ['Apprentice License', 'Toilet/Faucet Repair', 'Drain Cleaning', 'Basic Maintenance', 'Bilingual (English/Spanish)'], service_area: ['Gilbert', 'Mesa'], availability: { mon: '08:00-17:00', tue: '08:00-17:00', wed: '08:00-17:00', thu: '08:00-17:00', fri: '08:00-16:00' }, is_on_call: false, performance_score: 8.5, total_jobs_completed: 87, average_review_score: 4.7, created_at: daysAgo(45) },
]

// Summary metrics for dashboard
export const demoMetrics = {
  callsToday: 14,
  callsYesterday: 18,
  leadsToday: 5,
  conversionRate: 72,
  jobsBookedToday: 6,
  pipelineValue: 49850,
  revenueThisMonth: 77210,
  revenueLastMonth: 76003,
  minutesUsed: 1247,
  minutesIncluded: 2000,
  avgCallDuration: 214,
  answerRate: 96,
  escalationRate: 5,
  overdueInvoices: 4,
  overdueAmount: 10341,
  reviewAverage: 4.8,
  totalReviews: 312,
  followUpsSentToday: 7,
  reviewsRequestedToday: 4,
}
